# Generated by Django 3.1.5 on 2021-03-10 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'カスタムユーザー', 'verbose_name_plural': 'カスタムユーザー'},
        ),
        migrations.AlterModelTable(
            name='user',
            table='t_custom_user',
        ),
    ]
