version: '3.7'

services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile.prod
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/code/static
      - media_volume:/code/media
    expose:
        - 8000
    env_file: env/settings.prod.env
    depends_on:
      - postgres

  postgres:
    image: postgres:13.1
    volumes:
      - db:/var/lib/postgresql/data
    env_file: env/postgres.prod.env

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/code/static
      - media_volume:/code/media
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  db:
  static_volume:
  media_volume:
