version: '3.7'

services:
  web:
    build: ./web
    volumes:
      - ./web/:/code
    ports:
      - 8000:8000
    command: "python manage.py runserver 0.0.0.0:8000 --insecure"
    env_file: env/settings.env
    depends_on:
      - postgres

  postgres:
    image: postgres:13.1
    volumes:
      - db:/var/lib/postgresql/data
    env_file: env/postgres.env

volumes:
    db:
