# Generated by Django 3.1.5 on 2021-02-21 06:21

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import teams.models.profile
import teams.models.team
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('feature', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '特徴',
                'verbose_name_plural': '特徴',
                'db_table': 't_feature',
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'ゲーム',
                'verbose_name_plural': 'ゲーム',
                'db_table': 't_game',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=255)),
                ('awnser', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'よくある質問',
                'verbose_name_plural': 'よくある質問',
                'db_table': 't_question',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('teamname', models.CharField(db_index=True, max_length=15, unique=True, validators=[django.core.validators.MinLengthValidator(4), django.core.validators.RegexValidator(regex='[a-xA-Z0-9_]')], verbose_name='クランネーム')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.ImageField(blank=True, upload_to=teams.models.team.user_directory_path, validators=[teams.models.team.Team.validate_icon_image])),
                ('url', models.URLField(null=True)),
                ('description', models.CharField(max_length=255)),
                ('sponsor', models.CharField(max_length=50)),
                ('desired_condition', models.CharField(max_length=200)),
                ('disclosed', models.BooleanField(verbose_name='公開・非公開')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feature', models.ManyToManyField(related_name='team_feature', to='teams.Feature', verbose_name='特徴')),
                ('game_title', models.ManyToManyField(related_name='team_game_title', to='teams.Game')),
            ],
            options={
                'verbose_name': 'チーム',
                'verbose_name_plural': 'チーム',
                'db_table': 't_team',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='ニックネーム')),
                ('icon', models.ImageField(blank=True, default='default/profile_icon.png', upload_to=teams.models.profile.user_directory_path, validators=[teams.models.profile.UserProfile.validate_icon_image])),
                ('header', models.ImageField(blank=True, default='default/profile_header.jpg', upload_to=teams.models.profile.user_directory_path, validators=[teams.models.profile.UserProfile.validate_header_image])),
                ('is_owner', models.BooleanField(default=False)),
                ('introduction', models.CharField(max_length=140)),
                ('clip_url', models.URLField(blank=True, null=True)),
                ('desired_job_type', models.CharField(choices=[('player', '選手'), ('manger', 'マネージャー'), ('coach', 'コーチ')], max_length=100)),
                ('desired_condition', models.CharField(max_length=255, verbose_name='希望条件')),
                ('disclosed', models.BooleanField(default=True)),
                ('game_title', models.ManyToManyField(related_name='user_game_title', to='teams.Game')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team', to='teams.team')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ユーザープロフィール',
                'verbose_name_plural': 'ユーザープロフィール',
                'db_table': 't_user_profile',
            },
        ),
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.CharField(max_length=255, null=True, verbose_name='メッセージ')),
                ('invite_url', models.URLField(verbose_name='招待URL')),
                ('has_read', models.BooleanField(default=False)),
                ('is_proceeded', models.BooleanField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='send_invitations', to='teams.userprofile')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receive_invitations', to='teams.userprofile')),
            ],
            options={
                'verbose_name': '招待',
                'verbose_name_plural': '招待',
                'db_table': 't_invite',
            },
        ),
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.CharField(max_length=255, null=True, verbose_name='志望理由')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='send_apply', to='teams.userprofile')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receive_apply', to='teams.userprofile')),
            ],
            options={
                'verbose_name': 'リクエスト',
                'verbose_name_plural': 'リクエスト',
                'db_table': 't_apply',
            },
        ),
    ]
