# Generated by Django 3.1.5 on 2021-03-09 07:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberapproval',
            name='has_read',
            field=models.BooleanField(default=False, verbose_name='既読'),
        ),
        migrations.AlterField(
            model_name='memberapproval',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
