# Generated by Django 3.1.5 on 2021-03-10 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='name',
            field=models.CharField(default='ニックネーム', max_length=100, verbose_name='ニックネーム'),
        ),
    ]
