# Generated by Django 3.1.5 on 2021-02-26 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='desired_job_type',
            field=models.CharField(choices=[(1, '選手'), (2, 'マネージャー'), (3, 'コーチ')], max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='introduction',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
    ]
