# Generated by Django 3.1.5 on 2021-02-26 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('job', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='apply',
            name='desired_job',
            field=models.ManyToManyField(related_name='apply_desired_job', to='teams.Job'),
        ),
        migrations.AddField(
            model_name='invite',
            name='desired_job',
            field=models.ManyToManyField(related_name='invite_desired_job', to='teams.Job'),
        ),
    ]
