# Generated by Django 3.1.5 on 2021-02-19 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import teams.models.profile


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teams', '0002_auto_20210219_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='header',
            field=models.ImageField(blank=True, default='default_profile_header.jpg', upload_to=teams.models.profile.user_directory_path, validators=[teams.models.profile.UserProfile.validate_header_image]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
