# Generated by Django 3.1.5 on 2021-03-05 10:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_auto_20210305_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='sponsor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='teamname',
            field=models.CharField(db_index=True, max_length=15, unique=True, validators=[django.core.validators.MinLengthValidator(4), django.core.validators.RegexValidator(regex='[a-xA-Z0-9_]')], verbose_name='チームネーム'),
        ),
        migrations.AlterField(
            model_name='team',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
