# Generated by Django 3.1.5 on 2021-02-26 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_auto_20210226_2014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='desired_job_type',
        ),
        migrations.AddField(
            model_name='team',
            name='desired_job',
            field=models.ManyToManyField(related_name='team_desired_job', to='teams.Job'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='desired_job',
            field=models.ManyToManyField(related_name='profile_desired_job', to='teams.Job'),
        ),
    ]
