# Generated by Django 3.1.5 on 2021-02-26 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_auto_20210226_2104'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'verbose_name': 'ジョブ', 'verbose_name_plural': 'ジョブ'},
        ),
        migrations.AlterModelTable(
            name='job',
            table='t_job',
        ),
    ]
