FROM python:3.8

RUN mkdir /code
WORKDIR /code

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

COPY ./requirements.txt /code/requirements.txt
COPY ./entrypoint.prod.sh /code/entrypoint.prod.sh
COPY requirements.txt /code/

RUN pip install psycopg2 \
    && pip install --upgrade pip \
    && pip install -r requirements.txt

COPY . /code/

ENTRYPOINT ["/code/entrypoint.prod.sh"]