# Generated by Django 3.1.5 on 2021-02-08 04:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userclan',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_clan', to=settings.AUTH_USER_MODEL),
        ),
    ]
