# Generated by Django 3.1.5 on 2021-02-08 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clans', '0002_auto_20210208_1355'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'ゲーム',
                'verbose_name_plural': 'ゲーム',
                'db_table': 't_game',
            },
        ),
        migrations.AddField(
            model_name='clan',
            name='game_title',
            field=models.ManyToManyField(to='clans.Game'),
        ),
        migrations.AddField(
            model_name='userclan',
            name='game_title',
            field=models.ManyToManyField(to='clans.Game'),
        ),
    ]
